"""Pydantic schemas for the chatbot API."""

from pydantic import BaseModel, ConfigDict, Field


class ChatRequest(BaseModel):
    """Request payload for the chatbot API."""

    model_config = ConfigDict(extra="forbid")

    text: str = Field(..., description="The free-form text input from the user.")


class ChatResponse(BaseModel):
    """Response payload for the chatbot API."""

    model_config = ConfigDict(extra="forbid")

    text: str = Field(..., description="The response text generated by the AI.")
