"""initial trades and trade_services tables

Revision ID: 5d8a93629525
Revises: 
Create Date: 2026-04-23 13:25:18.092553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8a93629525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_category'), 'trades', ['category'], unique=False)
    op.create_index(op.f('ix_trades_name'), 'trades', ['name'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('trade_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('estimated_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_services_category'), 'trade_services', ['category'], unique=False)
    op.create_index(op.f('ix_trade_services_trade_id'), 'trade_services', ['trade_id'], unique=False)
    op.create_index(op.f('ix_trade_services_user_id'), 'trade_services', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_services_user_id'), table_name='trade_services')
    op.drop_index(op.f('ix_trade_services_trade_id'), table_name='trade_services')
    op.drop_index(op.f('ix_trade_services_category'), table_name='trade_services')
    op.drop_table('trade_services')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_name'), table_name='trades')
    op.drop_index(op.f('ix_trades_category'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
